config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'

  devise_for :users
  resources :photos do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :filename, PhotoUploader
	
	belongs_to :user
	has_many :comments

	validates :filename, presence: true
	validates :caption, length: { minimum: 4 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def index
		@photo = Photo.find(params[:photo_id])
		@comments = Comment.where(photo_id: params[:photo_id])
	end

  def new
  	@photo = Photo.find(params[:photo_id])
  	@comment = Comment.new
  end

  def create
  	@photo = Photo.find(params[:photo_id])
  	@comment = Comment.new(comment_params)
  	@comment.user = current_user
  	@comment.photo = @photo

  	if @comment.save
  		redirect_to photos_path, notice: "Your Reply has been saved"
  	end
  end

  private

  def comment_params
  	params.require(:comment).permit(:body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :authenticate_user!

  def index
  	@photos = current_user.photos
  end

  def new
  	@photo = Photo.new
  end

  def create
  	#@photo = Photo.new(photo_params)
  	#@photo.user = current_user

  	@photo = current_user.photos.build(photo_params) 

  	#this is an alternate way that is commonly used in production


  	if @photo.save 
  		redirect_to photos_path
  	else
  		render :new
  	end
  end

  def edit
  	@photo = current_user.photos.find(params[:id])
  end

  def update
  	#have to retrieve data from databse to update
  	@photo = current_user.photos.find(params[:id])

  	if @photo.update_attributes(photo_params) #if photo able to update these attributes
  		redirect_to photos_path
  	else
  		render :edit
  	end
  end

  private

  def photo_params
  	params.require(:photo).permit(:filename, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/index.html.erb
<%= image_tag @photo.filename, size:'300x300' %>

<hr>

<% @comments.each do |comment| %>
	<%= comment.body %><br>

	Created by: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago

<hr>
<% end %>

app/views/comments/new.html.erb
<div class="row">
	<div class="col-md-5">
	<%= simple_form_for [@photo, @comment] do |form| %>
		<%= form.input :body %>
		<%= form.submit 'Comment' %>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uploady" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Uploady</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       <!--  -->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/photos/edit.html.erb
<div class= "row">
	<div class="col-md-5">
<%= simple_form_for @photo, html: { class: 'form-horizontal'} do |form| %>
	<%= form.input :filename, label: 'Photo File' %>
	<%= form.input :caption %>
	<%= form.submit  'Upload Photo', class: 'btn btn-primary'%>
<% end %>
	</div>
<div class="col-md-7">
	<%= image_tag @photo.filename, size: '100x100' %>
</div>
</div>

app/views/photos/index.html.erb
<h1>All Photos</h1>

<p>
	<strong><%= link_to "Upload a new Photo", new_photo_path %></strong>
</p>

<%= simple_table_for @photos, with: PhotosTable %>

app/views/photos/new.html.erb
<div class="row">
	<div class="col-md-5">
<%= simple_form_for @photo, html: { class: 'form-horizontal'} do |form| %>
	<%= form.input :filename, label: 'Photo File' %>
	<%= form.input :caption %>
	<%= form.submit  'Upload Photo', class: 'btn btn-primary'%>
<% end %>
	</div>
</div>